/*
 * tests/lib/test_tls_posix.c — Real TLS connection tests for hal_tls_posix
 *
 * Tests the real mbedTLS implementation in hal/posix/ops/hal_tls_posix.c.
 * Spawns a Python TLS echo server (tests/lib/scripts/tls_echo_server.py)
 * and exercises the full connect/send/recv/disconnect cycle.
 *
 * Certs are generated by tests/lib/scripts/gen_tls_test_certs.sh and
 * live in /tmp/embediq_tls_test/.
 *
 * Uses extern declarations for HAL accessors (not HAL headers) to
 * satisfy boundary_checker.py layer rules for tests/.
 *
 * @author  Ritesh Anand
 * @company embediq.com | ritzylab.com
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#define _POSIX_C_SOURCE 200809L

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <stdint.h>
#include <stdbool.h>
#include <pthread.h>
#include "ops/embediq_tls.h"
#include "embediq_config.h"

/* Use extern declarations — not HAL headers (boundary_checker rule for tests/) */
extern const embediq_tls_ops_t *hal_tls_posix_ops_slot(uint8_t idx);
extern const embediq_tls_ops_t *hal_tls_posix_ops(void);

/* Test-local buffer sizes */
#define TLS_CMD_BUF_SIZE   512u   /* shell command string for system() */
#define TLS_TEST_RECV_BUF   32u   /* echo test receive buffer */

/* ---------------------------------------------------------------------------
 * Test infrastructure
 * ------------------------------------------------------------------------- */

#define CERT_DIR      "/tmp/embediq_tls_test"
#define TEST_PORT     19876

static int g_tests_run    = 0;
static int g_tests_failed = 0;

#define ASSERT(cond, msg) do {                                              \
    g_tests_run++;                                                          \
    if (!(cond)) {                                                          \
        fprintf(stderr, "FAIL  %-56s  %s:%d — %s\n",                      \
                __func__, __FILE__, __LINE__, (msg));                       \
        g_tests_failed++;                                                   \
    } else {                                                                \
        printf("PASS  %s\n", __func__);                                     \
    }                                                                       \
} while (0)

/* ---------------------------------------------------------------------------
 * Cert file helpers
 * ------------------------------------------------------------------------- */

static char *read_pem_file(const char *path)
{
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    rewind(f);
    char *buf = malloc((size_t)(sz + 1));
    if (!buf) { fclose(f); return NULL; }
    fread(buf, 1, (size_t)sz, f);
    buf[sz] = '\0';
    fclose(f);
    return buf;
}

/* ---------------------------------------------------------------------------
 * TLS echo server lifecycle
 * ------------------------------------------------------------------------- */

static void start_echo_server(int port, bool mutual)
{
    char cmd[TLS_CMD_BUF_SIZE];
    const char *mutual_flag = mutual ? "--mutual" : "";
    snprintf(cmd, sizeof(cmd),
        "python3 " EMBEDIQ_REPO_ROOT "/tests/lib/scripts/tls_echo_server.py"
        " %d %s/server.crt %s/server.key %s/ca.crt %s &",
        port, CERT_DIR, CERT_DIR, CERT_DIR, mutual_flag);
    (void)system(cmd);
    struct timespec ts_wait = { .tv_sec = 0, .tv_nsec = 200000000L };
    nanosleep(&ts_wait, NULL);   /* 200 ms — let Python server start */
}

static void stop_echo_server(void)
{
    (void)system("pkill -f tls_echo_server.py 2>/dev/null || true");
    struct timespec ts_wait = { .tv_sec = 0, .tv_nsec = 50000000L };
    nanosleep(&ts_wait, NULL);
}

/* ---------------------------------------------------------------------------
 * Callback synchronisation
 * ------------------------------------------------------------------------- */

typedef struct {
    embediq_tls_err_t result;
    bool              fired;
    pthread_mutex_t   mu;
    pthread_cond_t    cv;
} cb_state_t;

static void connect_cb(embediq_tls_err_t result, void *user_ctx)
{
    cb_state_t *st = (cb_state_t *)user_ctx;
    pthread_mutex_lock(&st->mu);
    st->result = result;
    st->fired  = true;
    pthread_cond_signal(&st->cv);
    pthread_mutex_unlock(&st->mu);
}

static embediq_tls_err_t wait_for_connect(cb_state_t *st, unsigned timeout_ms)
{
    struct timespec ts;
    clock_gettime(CLOCK_REALTIME, &ts);
    ts.tv_sec  += (long)(timeout_ms / 1000u);
    ts.tv_nsec += (long)((timeout_ms % 1000u) * 1000000L);
    if (ts.tv_nsec >= 1000000000L) { ts.tv_sec++; ts.tv_nsec -= 1000000000L; }

    pthread_mutex_lock(&st->mu);
    while (!st->fired) {
        if (pthread_cond_timedwait(&st->cv, &st->mu, &ts) != 0) {
            pthread_mutex_unlock(&st->mu);
            return EMBEDIQ_TLS_ERR_TIMEOUT;
        }
    }
    embediq_tls_err_t result = st->result;
    pthread_mutex_unlock(&st->mu);
    return result;
}

static void cb_state_init(cb_state_t *st)
{
    st->result = EMBEDIQ_TLS_ERR_NOT_CONFIGURED;
    st->fired  = false;
    pthread_mutex_init(&st->mu, NULL);
    pthread_cond_init(&st->cv, NULL);
}

/* ---------------------------------------------------------------------------
 * Tests
 * ------------------------------------------------------------------------- */

static void test_configure_server_only(void)
{
    char *ca = read_pem_file(CERT_DIR "/ca.crt");
    ASSERT(ca != NULL, "CA cert file must exist — run gen_tls_test_certs.sh first");
    if (!ca) return;

    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    embediq_tls_err_t rc = ops->configure(ca, NULL, NULL);
    ASSERT(rc == EMBEDIQ_TLS_OK, "server-only configure must return EMBEDIQ_TLS_OK");
    free(ca);
}

static void test_configure_mutual_tls(void)
{
    char *ca  = read_pem_file(CERT_DIR "/ca.crt");
    char *cc  = read_pem_file(CERT_DIR "/client.crt");
    char *ck  = read_pem_file(CERT_DIR "/client.key");
    ASSERT(ca && cc && ck, "mutual TLS cert files must exist");
    if (!ca || !cc || !ck) { free(ca); free(cc); free(ck); return; }

    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    embediq_tls_err_t rc = ops->configure(ca, cc, ck);
    ASSERT(rc == EMBEDIQ_TLS_OK, "mutual TLS configure must return EMBEDIQ_TLS_OK");
    free(ca); free(cc); free(ck);
}

static void test_connect_not_configured(void)
{
    /* Get slot 0, but do NOT call configure first — slot may still be configured
     * from previous test. Reset by calling configure with a deliberate bad cert. */
    const embediq_tls_ops_t *ops = hal_tls_posix_ops_slot(0u);

    /* Use a fresh slot if we have 2 — slot 1 starts unconfigured */
#if EMBEDIQ_TLS_MAX_CONNECTIONS >= 2
    ops = hal_tls_posix_ops_slot(1u);
#endif
    (void)ops; /* intentionally ignore — slot 1 is unconfigured from pool_init */

    /* Directly test not-configured path on a fresh slot that was never configured */
    /* Slot 1 is guaranteed not configured at startup */
#if EMBEDIQ_TLS_MAX_CONNECTIONS >= 2
    const embediq_tls_ops_t *fresh = hal_tls_posix_ops_slot(1u);
    cb_state_t st; cb_state_init(&st);
    embediq_tls_err_t rc = fresh->connect_async("127.0.0.1", TEST_PORT, "localhost",
                                                  connect_cb, &st);
    ASSERT(rc == EMBEDIQ_TLS_ERR_NOT_CONFIGURED,
           "connect_async without configure must return EMBEDIQ_TLS_ERR_NOT_CONFIGURED");
#else
    /* With only 1 slot, skip this test — it was already configured above */
    g_tests_run++;
    printf("PASS  test_connect_not_configured (skipped — single-slot build)\n");
#endif
}

static void test_connect_success(void)
{
    char *ca = read_pem_file(CERT_DIR "/ca.crt");
    ASSERT(ca != NULL, "CA cert must exist");
    if (!ca) return;

    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    embediq_tls_err_t rc = ops->configure(ca, NULL, NULL);
    ASSERT(rc == EMBEDIQ_TLS_OK, "configure must succeed");
    free(ca);
    if (rc != EMBEDIQ_TLS_OK) return;

    start_echo_server(TEST_PORT, false);

    cb_state_t st; cb_state_init(&st);
    rc = ops->connect_async("127.0.0.1", TEST_PORT, "localhost", connect_cb, &st);
    ASSERT(rc == EMBEDIQ_TLS_OK, "connect_async must initiate successfully");

    embediq_tls_err_t result = wait_for_connect(&st, 5000u);
    ASSERT(result == EMBEDIQ_TLS_OK, "TLS handshake with local echo server must succeed");

    ops->disconnect();
    stop_echo_server();
}

static void test_connect_wrong_ca(void)
{
    /* Use a self-signed cert as CA — it won't verify the server cert */
    char *wrong_ca = read_pem_file(CERT_DIR "/client.crt");
    ASSERT(wrong_ca != NULL, "client.crt must exist for wrong-CA test");
    if (!wrong_ca) return;

    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    embediq_tls_err_t rc = ops->configure(wrong_ca, NULL, NULL);
    free(wrong_ca);
    ASSERT(rc == EMBEDIQ_TLS_OK, "configure with wrong CA must succeed at load time");
    if (rc != EMBEDIQ_TLS_OK) return;

    start_echo_server(TEST_PORT + 1, false);

    cb_state_t st; cb_state_init(&st);
    rc = ops->connect_async("127.0.0.1", TEST_PORT + 1, "localhost", connect_cb, &st);
    ASSERT(rc == EMBEDIQ_TLS_OK, "connect_async must initiate");

    embediq_tls_err_t result = wait_for_connect(&st, 5000u);
    ASSERT(result == EMBEDIQ_TLS_ERR_CERT_VERIFY,
           "connection with wrong CA must fail with EMBEDIQ_TLS_ERR_CERT_VERIFY");

    stop_echo_server();
}

static void test_send_recv(void)
{
    char *ca = read_pem_file(CERT_DIR "/ca.crt");
    ASSERT(ca != NULL, "CA cert must exist");
    if (!ca) return;

    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    embediq_tls_err_t rc = ops->configure(ca, NULL, NULL);
    free(ca);
    if (rc != EMBEDIQ_TLS_OK) { ASSERT(false, "configure failed"); return; }

    start_echo_server(TEST_PORT + 2, false);

    cb_state_t st; cb_state_init(&st);
    rc = ops->connect_async("127.0.0.1", TEST_PORT + 2, "localhost", connect_cb, &st);
    if (wait_for_connect(&st, 5000u) != EMBEDIQ_TLS_OK) {
        ASSERT(false, "connect failed for send/recv test");
        stop_echo_server();
        return;
    }

    const uint8_t ping[] = "PING";
    rc = ops->send(ping, (uint16_t)sizeof(ping));
    ASSERT(rc == EMBEDIQ_TLS_OK, "send PING must succeed");

    uint8_t buf[TLS_TEST_RECV_BUF];
    int32_t n = ops->recv(buf, (uint16_t)sizeof(buf), 3000u);
    ASSERT(n == (int32_t)sizeof(ping), "recv must return same bytes as sent");
    ASSERT(memcmp(buf, ping, (size_t)sizeof(ping)) == 0, "echoed data must match sent data");

    ops->disconnect();
    stop_echo_server();
}

static void test_disconnect(void)
{
    const embediq_tls_ops_t *ops = hal_tls_posix_ops();
    /* disconnect on a non-connected slot must not crash */
    embediq_tls_err_t rc = ops->disconnect();
    ASSERT(rc == EMBEDIQ_TLS_OK, "disconnect on non-connected slot must return OK");
}

#if EMBEDIQ_TLS_MAX_CONNECTIONS >= 2
static void test_slot_isolation(void)
{
    char *ca = read_pem_file(CERT_DIR "/ca.crt");
    ASSERT(ca != NULL, "CA cert must exist");
    if (!ca) return;

    const embediq_tls_ops_t *s0 = hal_tls_posix_ops_slot(0u);
    const embediq_tls_ops_t *s1 = hal_tls_posix_ops_slot(1u);

    ASSERT(s0 != s1, "slot 0 and slot 1 must be different ops tables");

    /* Configure both slots independently */
    embediq_tls_err_t rc0 = s0->configure(ca, NULL, NULL);
    embediq_tls_err_t rc1 = s1->configure(ca, NULL, NULL);
    free(ca);

    ASSERT(rc0 == EMBEDIQ_TLS_OK, "slot 0 configure must succeed");
    ASSERT(rc1 == EMBEDIQ_TLS_OK, "slot 1 configure must succeed");

    /* Connect both slots to independent echo servers */
    start_echo_server(TEST_PORT + 3, false);

    cb_state_t st0, st1;
    cb_state_init(&st0);
    cb_state_init(&st1);

    rc0 = s0->connect_async("127.0.0.1", TEST_PORT + 3, "localhost", connect_cb, &st0);
    ASSERT(rc0 == EMBEDIQ_TLS_OK, "slot 0 connect_async must initiate");

    embediq_tls_err_t res0 = wait_for_connect(&st0, 5000u);
    ASSERT(res0 == EMBEDIQ_TLS_OK, "slot 0 handshake must succeed");

    s0->disconnect();
    stop_echo_server();

    /* slot 1 was configured independently — its ops table must remain intact
     * after slot 0's configure+connect+disconnect sequence. */
    ASSERT(s1 != NULL, "slot 1 ops table must remain non-NULL after slot 0 operations");
    ASSERT(s1->version == EMBEDIQ_TLS_OPS_VERSION,
           "slot 1 version must be intact after slot 0 configure+connect+disconnect");
}
#endif

/* ---------------------------------------------------------------------------
 * main
 * ------------------------------------------------------------------------- */

int main(void)
{
    printf("\n--- TLS POSIX implementation tests ---\n");
    printf("Cert dir: %s\n\n", CERT_DIR);

    /* Generate certs if not present */
    (void)system("bash " EMBEDIQ_REPO_ROOT "/tests/lib/scripts/gen_tls_test_certs.sh"
                 " 2>/dev/null || true");

    test_configure_server_only();
    test_configure_mutual_tls();
    test_connect_not_configured();
    test_connect_success();
    test_connect_wrong_ca();
    test_send_recv();
    test_disconnect();
#if EMBEDIQ_TLS_MAX_CONNECTIONS >= 2
    test_slot_isolation();
#endif

    printf("\n%d/%d tests passed.\n",
           g_tests_run - g_tests_failed, g_tests_run);
    return g_tests_failed > 0 ? 1 : 0;
}
