#!/usr/bin/env bash
# =============================================================================
# gen_dev_cert.sh — DEVELOPMENT-ONLY CERT GENERATOR
#
# PURPOSE: Generates a self-signed CA + per-device certificate for LOCAL TESTING.
# This script is run ONCE on a developer's machine, not by firmware.
#
# WARNING: Certs generated by this script are self-signed. They will NOT be
# accepted by a production Mosquitto broker configured with cafile (OEM CA).
# This script is NEVER called by firmware at runtime.
#
# PRODUCTION: OEM signing service generates per-device certs at the factory.
#             See ARCHITECTURE.md: fb_provisioning — Two-Place Model.
#
# USAGE: sudo bash scripts/gen_dev_cert.sh [output_dir] [device_id]
#   output_dir defaults to /etc/embediq/certs
#   device_id  defaults to dev-device-001
#
# @author  Ritesh Anand
# @company embediq.com | ritzylab.com
# SPDX-License-Identifier: Apache-2.0
# =============================================================================

set -e

CERT_DIR="${1:-/etc/embediq/certs}"
DEVICE_ID="${2:-dev-device-001}"
DAYS=365

mkdir -p "$CERT_DIR"

echo "[gen_dev_cert] Generating development CA..."
openssl genrsa -out "$CERT_DIR/ca.key" 2048
openssl req -new -x509 -days "$DAYS" -key "$CERT_DIR/ca.key" -out "$CERT_DIR/ca.crt" \
  -subj "/CN=EmbedIQ-Dev-CA/O=EmbedIQ Dev/C=US"

echo "[gen_dev_cert] Generating device key and CSR..."
openssl genrsa -out "$CERT_DIR/device.key" 2048
openssl req -new -key "$CERT_DIR/device.key" -out "$CERT_DIR/device.csr" \
  -subj "/CN=$DEVICE_ID/O=EmbedIQ Dev/C=US"

echo "[gen_dev_cert] Signing device certificate with dev CA..."
openssl x509 -req -days "$DAYS" -in "$CERT_DIR/device.csr" \
  -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" -CAcreateserial \
  -out "$CERT_DIR/device.crt"

rm -f "$CERT_DIR/device.csr" "$CERT_DIR/ca.srl"

echo "[gen_dev_cert] Done. Files written to $CERT_DIR:"
echo "  ca.crt      (DEV CA — configure Mosquitto with: cafile $CERT_DIR/ca.crt)"
echo "  device.crt  (Device cert — CN=$DEVICE_ID)"
echo "  device.key  (Device private key)"
echo ""
echo "WARNING: These are self-signed DEV certs. Not for production use."
